export const showcases = [
  {
    id: 9,
    title: 'Snowcrash SC-HIRO',
    cover: 'scHiro.svg',
    description: `Snowcrash SC-HIRO is a product of snowcrash team that makes you able to generate any type of music by communicating with AI chatbot.`,
    myRole: [
      `Implemented the studio inspired by open source signal.vercel.app project but much more awesome as you can communicate with AI and generate different types of musics and manipulate it's notes as you want.`,
      `Implementing reusable UI components for it's design system and theme.`,
    ],
    tag: ['AI'],
    website: 'http://www.snowcrash.com',
    technologies: ['Next.js', 'Typescript', 'Tailwind', 'Axios', 'MobX'],
    role: 'Front-end developer',
    type: 'Via_Insanustu',
    images: [
      '/images/companies/scHiro/1.svg',
      '/images/companies/scHiro/2.svg',
      '/images/companies/scHiro/3.svg',
      '/images/companies/scHiro/4.svg',
      '/images/companies/scHiro/5.svg',
      '/images/companies/scHiro/6.svg',
      '/images/companies/scHiro/7.svg',
      '/images/companies/scHiro/8.svg',
    ],
  },
  {
    id: 7,
    title: 'Unigatchi(Laguna Games)',
    cover: 'lagunaGames.svg',
    description: `Crypto Unicorns is a unique and exciting game that allows players to embark on a magical journey into a world of wonder and adventure. With its innovative use of blockchain technology, the game offers a new level of interactivity and engagement that is sure to captivate players of all ages.`,
    tag: ['NFT', 'Blockchain'],
    type: 'Via_Insanustu',
    website: 'https://laguna.games/',
    technologies: ['React', 'Typescript', 'Svelte', 'Three.js', 'Javascript', 'web3-react'],
    role: 'Front-end developer',
    myRole: [
      `Implemented The project ones using svelte and once using React.`,
      `Implemented many small web apps for the community using Vanilla Javascript for ML model training.`,
      `Worked on connecting to crypto wallets using web3-react.`,
      'Implemented full responsiveness of the app for different devices such as Mobiles, Tablets, and Desktops.',
    ],
    images: [
      '/images/companies/LagunaGames/1.svg',
      '/images/companies/LagunaGames/2.svg',
      '/images/companies/LagunaGames/3.svg',
    ],
  },
  {
    id: 0,
    title: 'Upperly',
    cover: 'upperly.svg',
    description: `Upperly is a platform that provides valuable insights to consumers who are looking to make informed decisions
    about their purchases. It offers a wide range of information on various products and services, allowing users to compare and contrast
    different options before making a final decision.`,
    myRole: [
      `Refactored an outdated project, transitioning it to a new
    website using cutting-edge technologies.`,
      `Lead a team of frontend developers, ensuring effective communication and successful task completion.`,
      `Responsible for software architecture,
    coding, and supervising the development process to ensure the delivery of a robust and efficient application.`,
      `Implemented new features to meet it's clients needs.`,
    ],
    tag: ['Automation'],
    website: 'http://upperly.net',
    technologies: ['React', 'Typescript', 'Redux', 'Ant-design', 'Auth0'],
    role: 'Front-end developer',
    type: 'Via_TwelfthDream',
    images: [
      '/images/companies/Upperly/1.svg',
      '/images/companies/Upperly/2.svg',
      '/images/companies/Upperly/3.svg',
      '/images/companies/Upperly/4.svg',
      '/images/companies/Upperly/5.svg',
      '/images/companies/Upperly/6.svg',
    ],
  },
  {
    id: 9982,
    title: 'Cakewalk',
    cover: 'cakewalk.svg',
    description: ` Cakewalk is an AI platform that transforms teams into AI super users, offering features like team workspaces,
          prompt libraries, prompt templates, and the ability to integrate different AI models. With options for Lite
          and Pro plans, users can access various models, shared workspaces, prompt templates, and more.
        
          The platform also offers automated workflows, user analytics, and reporting. Cakewalk is currently in private
          beta with pricing subject to change.`,
    myRole: [
      `Implemented features like auto generating, creating and updating prompts, etc...`,
      `Resolved old bugs of the codebase that were causing lots of performance issues.`,
    ],
    tag: ['AI'],
    website: 'https://www.cakewalk.ai/',
    technologies: ['Next.js', 'Typescript', 'Tailwind', 'Shadcn'],
    role: 'Front-end developer',
    type: 'Via_Harken',
    images: [
      '/images/companies/Cakewalk/1.svg',
      '/images/companies/Cakewalk/2.svg',
      '/images/companies/Cakewalk/3.svg',
      '/images/companies/Cakewalk/4.svg',
      '/images/companies/Cakewalk/5.svg',
      '/images/companies/Cakewalk/6.svg',
      '/images/companies/Cakewalk/7.svg',
      '/images/companies/Cakewalk/8.svg',
    ],
  },

  {
    id: 2,
    title: 'RWSolutions',
    cover: 'rwsolutions.svg',
    description: `RWSolutions is in the business of providing safe and reliable partnerships networking for freight forwarders worldwide. 
    It has more than 900+ forwarding members covering 100 countries.`,
    tag: ['Automation'],
    website: 'http://www.rwsolutions.com',
    technologies: ['React', 'Typescript', 'Redux-toolkit', 'Styled-components', 'Ant-design'],
    role: 'Front-end developer',
    type: 'Via_TwelfthDream',
    myRole: [
      `Implemented The dashboard pages from scratch.`,
      `Implemented Notification system using firebase.`,
      'Created new components and also re-customized ant-design system components.',
    ],
    images: [
      '/images/companies/RwSolutions/1.svg',
      '/images/companies/RwSolutions/2.svg',
      '/images/companies/RwSolutions/3.svg',
      '/images/companies/RwSolutions/4.svg',
      '/images/companies/RwSolutions/5.svg',
      '/images/companies/RwSolutions/6.svg',
      '/images/companies/RwSolutions/7.svg',
      '/images/companies/RwSolutions/8.svg',
      '/images/companies/RwSolutions/9.svg',
      '/images/companies/RwSolutions/10.svg',
      '/images/companies/RwSolutions/11.svg',
      '/images/companies/RwSolutions/12.svg',
    ],
  },
  {
    id: 3,
    title: 'CopyCat',
    cover: 'copycat.svg',
    description: `CopyCat helps developers build UI 50% faster by generating reusable UI code from your Figma designs.`,
    tag: ['AI'],
    website: 'https://copycat.dev',
    technologies: ['React', 'Typescript', 'Parcel', 'Redux-toolkit', 'Axios'],
    role: 'Front-end developer',
    type: 'Via_Insanustu',
    myRole: [`Worked on figma-plugin based react app to improve UI and functionalities.`],
    images: [
      '/images/companies/Copycat/1.svg',
      '/images/companies/Copycat/2.svg',
      '/images/companies/Copycat/3.svg',
      '/images/companies/Copycat/4.svg',
      '/images/companies/Copycat/5.svg',
    ],
  },
  {
    id: 4,
    title: 'Hotg.ai',
    cover: 'hotg.svg',
    description: ` Hammer of the Gods (HOT-G) builds developer experience tools and infrastructure for federated computing -
    devices, cloud, and cross data silos.`,
    tag: ['AI'],
    website: 'https://hotg.ai/',
    technologies: ['React', 'Typescript', 'React-flow'],
    role: 'Front-end developer',
    type: 'Via_Insanustu',
    myRole: [`Worked on Node-base interactive diagram.`],
    images: ['/images/companies/Hotg.ai/1.svg', '/images/companies/Hotg.ai/2.svg', '/images/companies/Hotg.ai/3.svg'],
  },
  {
    id: 6,
    title: 'RW Navigator',
    cover: 'rwNavigator.svg',
    description: `RWSolutions is in the business of providing safe and reliable partnerships networking for freight forwarders worldwide. 
    It has more than 900+ forwarding members covering 100 countries.`,
    tag: ['Automation'],
    website: 'http://www.rwsolutions.com',
    technologies: ['React', 'Typescript', 'Redux-toolkit', 'Styled-components', 'Ant-design'],
    role: 'Front-end developer',
    type: 'Via_TwelfthDream',
    myRole: [
      `Implemented The dashboard pages from scratch.`,
      `Implemented Notification and online chatting system using firebase and websocket.`,
      'Created new components and also re-customized ant-design system components.',
      'Implemented full responsiveness of the app for different devices such as Mobiles, Tablets, and Desktops.',
    ],
    images: [
      '/images/companies/RwNavigator/1.svg',
      '/images/companies/RwNavigator/2.svg',
      '/images/companies/RwNavigator/3.svg',
      '/images/companies/RwNavigator/4.svg',
      '/images/companies/RwNavigator/5.svg',
      '/images/companies/RwNavigator/6.svg',
      '/images/companies/RwNavigator/7.svg',
      '/images/companies/RwNavigator/8.svg',
      '/images/companies/RwNavigator/9.svg',
      '/images/companies/RwNavigator/10.svg',
    ],
  },

  {
    id: 8,
    title: 'Weld Studio',
    cover: 'weldStudio.svg',
    description: `Weld Studio is prototyping software. Consider the prototype as the early sample of the final product model. Weld Studio profoundly contributes to software development at the stage of prototyping. It's for healthcare data teams dealing with data silos.`,
    tag: ['AI'],
    type: 'Via_Insanustu',
    website: 'https://hotg.ai/healthcare/',
    technologies: ['React', 'Typescript', 'React-flow'],
    role: 'Front-end developer',
    myRole: [`Implemented the whole project using react.`, `Created reusable components for it's design system.`],
    images: [
      '/images/companies/WeldStudio/1.svg',
      '/images/companies/WeldStudio/2.svg',
      '/images/companies/WeldStudio/3.svg',
      '/images/companies/WeldStudio/4.svg',
      '/images/companies/WeldStudio/5.svg',
      '/images/companies/WeldStudio/6.svg',
      '/images/companies/WeldStudio/7.svg',
      '/images/companies/WeldStudio/8.svg',
      '/images/companies/WeldStudio/9.svg',
      '/images/companies/WeldStudio/10.svg',
      '/images/companies/WeldStudio/11.svg',
    ],
  },

  {
    id: 1,
    title: 'Snowcrash',
    cover: 'snowcrash.svg',
    description: `Snowcrash empowers artists, cultural icons, content creators, influencers, celebrities and brands to access
    untapped creative and economic potential of NFTs by harnessing the latent value in already-created properties
    and by designing new digital assets and virtual experiences.`,
    myRole: [
      `Implemented Dashboard pages for buying and selling NFT assets by users.`,
      `Created new reusable components for it's design system.`,
      `Implemented chat section for communicating with AI chatbot.`,
      `Implemented new landing pages.`,
    ],
    tag: ['NFT', 'AI'],
    technologies: ['Next.js', 'Typescript', 'Tailwind', 'Open-ai'],
    role: 'Front-end developer',
    type: 'Via_Insanustu',
    images: [
      '/images/companies/Snowcrash/1.svg',
      '/images/companies/Snowcrash/2.svg',
      '/images/companies/Snowcrash/3.svg',
      '/images/companies/Snowcrash/4.svg',
      '/images/companies/Snowcrash/5.svg',
      '/images/companies/Snowcrash/6.svg',
      '/images/companies/Snowcrash/7.svg',
      '/images/companies/Snowcrash/8.svg',
    ],
  },
];

export const logos = [
  'Harken.svg',
  'hotg.svg',
  'copycat.svg',
  'insanustu.svg',
  'cakewalk.svg',
  'rwsolutions.svg',
  'rwNavigator.svg',
  'lagunaGames.svg',
  'snowcrash.svg',
  'twelfthDream.svg',
  'weldStudio.svg',
  'upperly.svg',
  'bitrafi.svg',
];

export const expertise = [
  'Next.js',
  ' React',
  ' TypeScript',
  ' JavaScript',
  ' HTML',
  ' CSS',
  ' Sass',
  ' Tailwind CSS',
  ' Redux',
  ' Redux Toolkit',
  ' Zustand',
  'React Query (TanStack)',
  ' Material-Ul',
  ' Ant Design',
  ' ShadCN',
  ' Git',
  ' GitHub',
  ' GitLab',
  ' Azure DevOps',
  ' webSocket',
];
export const familiarSkills = [
  'Node.js',
  ' Express.js',
  ' MongoDB',
  ' PostgreSQL',
  ' React Native',
  ' Webpack',
  ' Docker',
  ' Framer-motion',
  ' React testing Library (Unit testing & integration testing)',
  ' Jest',
  ' Cypress',
  ' PW',
];
export const softSkills = [
  'Team Collaboration',
  'Problem Solving',
  'Adaptability',
  'Fast-learner',
  'Flexibility',
  'Time-management',
  'Passion',
];
